3. Core Business Analytics Queries


1. -- What is the total revenue generated by the retail store?

   SELECT
   SUM(total_amount) AS total_revenue
   FROM sales;
   
2. -- Which product categories generate the highest revenue?

    SELECT
    product_category,
    SUM(total_amount) AS revenue
    FROM sales
    GROUP BY product_category
    ORDER BY revenue DESC;
     
3. -- Who are the top 10 customers based on total spending?

    SELECT
    customer_id,
    SUM(total_amount) AS total_spent
    FROM sales
    GROUP BY customer_id
    ORDER BY total_spent DESC
    LIMIT 10;
    
4. -- What is the average order value of transactions?

    SELECT
    ROUND(AVG(total_amount),2) AS average_order_value
    FROM sales;
    
5. -- How much revenue is generated by each gender group?

    SELECT
    gender,
    SUM(total_amount) AS revenue
    FROM sales
    GROUP BY gender;
    
6. -- Which product category sells the highest quantity of items?

    SELECT
    product_category,
    SUM(quantity) AS total_quantity
    FROM sales
    GROUP BY product_category
    ORDER BY total_quantity DESC;


7. -- How does revenue vary across different months?

    SELECT
    MONTH(date) AS month,
    SUM(total_amount) AS monthly_sales
    FROM sales
    GROUP BY month
    ORDER BY month;
    
8. -- Which age group contributes the most to total revenue?

SELECT
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS age_group,
    SUM(total_amount) AS total_revenue
FROM sales
GROUP BY age_group
ORDER BY total_revenue DESC;

9. -- What is the average quantity purchased per transaction?

SELECT
    ROUND(AVG(quantity), 2) AS average_quantity_per_transaction
FROM sales;
